import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, posix, win32 } from "node:path";
import { restrictAccess } from "./private-files.mjs";

const TOKEN_MINIMUM_LENGTH = 20;

export function parseEnvFile(text) {
  return Object.fromEntries(
    text
      .split(/\r?\n/)
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => {
        const index = line.indexOf("=");
        return [
          line.slice(0, index).trim(),
          line
            .slice(index + 1)
            .trim()
            .replace(/^"(.*)"$/, "$1"),
        ];
      }),
  );
}

export function generateAccessToken() {
  return randomBytes(32).toString("base64url");
}

// A token is unusable if it is missing, too short to resist guessing, or still
// the placeholder shipped in .env.example.
export function needsAccessToken(value) {
  if (!value) return true;
  if (value.length < TOKEN_MINIMUM_LENGTH) return true;
  return value.startsWith("replace-with");
}

// The per-user state directory the packaged app owns. Kept here rather than in
// the supervisor so the same default applies to every entry point.
export function defaultStateRoot(
  platform = process.platform,
  env = process.env,
) {
  if (platform === "win32")
    return win32.join(
      env.LOCALAPPDATA ?? win32.join(homedir(), "AppData", "Local"),
      "HoshiStream",
    );
  return posix.join(homedir(), "Library", "Application Support", "HoshiStream");
}

export function defaultMediaDir(platform = process.platform) {
  return platform === "win32"
    ? win32.join(homedir(), "Videos")
    : posix.join(homedir(), "Movies");
}

function renderEnvFile({
  accessToken,
  pointerPushSecret,
  mediaDir,
  addonPort,
}) {
  return `# Generated by HoshiStream on first run. Edit freely.

ADDON_PORT=${addonPort}

# Guards the management API and appears in your tokenized add-on URL.
ACCESS_TOKEN=${accessToken}

# Folder the app scans for local media.
MEDIA_DIR=${mediaDir}

# Fallback LAN speed (Mbps); the app measures the real link speed at startup.
HOME_SPEED_MBPS=10

# Opt-in stream repair (ADR 0010).
TRANSCODE_ENABLED=false

# Remote pointer (optional, ADR 0013): use Activity > Remote pointer to enable
# a service. Saving setup sends nothing; registration and updates are manual.
# This per-install credential authenticates requests to the chosen service.
# POINTER_URL=https://your-pointer.vercel.app
POINTER_PUSH_SECRET=${pointerPushSecret}
`;
}

async function writePrivateFile(path, contents) {
  const temporary = `${path}.tmp`;
  await writeFile(temporary, "", { mode: 0o600 });
  await restrictAccess(temporary);
  await writeFile(temporary, contents, { mode: 0o600 });
  await rename(temporary, path);
}

/**
 * Make a fresh machine runnable: create the state directory and a .env holding
 * a generated access token. Existing files are preserved; only a missing or
 * placeholder token is replaced. Returns the parsed environment.
 */
export async function ensureFirstRunSetup({
  projectRoot,
  pointerStateRoot = join(projectRoot, "native-data"),
  mediaDir = defaultMediaDir(),
  addonPort = 7001,
}) {
  await mkdir(projectRoot, { recursive: true, mode: 0o700 });
  const envPath = join(projectRoot, ".env");
  let priorPointerSetup = false;
  for (const name of ["pointer-state.json", "pointer-settings.json"]) {
    try {
      await stat(join(pointerStateRoot, name));
      priorPointerSetup = true;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }

  let existing = null;
  try {
    existing = await readFile(envPath, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }

  if (existing === null) {
    if (priorPointerSetup)
      throw new Error(
        "Existing pointer setup has lost its .env. Restore the private configuration backup before restarting; credentials were not replaced.",
      );
    const accessToken = generateAccessToken();
    const pointerPushSecret = generateAccessToken();
    await writePrivateFile(
      envPath,
      renderEnvFile({ accessToken, pointerPushSecret, mediaDir, addonPort }),
    );
    return {
      environment: parseEnvFile(await readFile(envPath, "utf8")),
      firstRun: true,
    };
  }

  const environment = parseEnvFile(existing);
  let contents = existing;
  if (needsAccessToken(environment.ACCESS_TOKEN)) {
    if (priorPointerSetup || environment.POINTER_URL)
      throw new Error(
        "Existing pointer setup has lost its ACCESS_TOKEN. Restore the private configuration backup; the installation identity was not replaced.",
      );
    const accessToken = generateAccessToken();
    contents = /^ACCESS_TOKEN=.*$/m.test(contents)
      ? contents.replace(/^ACCESS_TOKEN=.*$/m, `ACCESS_TOKEN=${accessToken}`)
      : `${contents.replace(/\n*$/, "\n")}ACCESS_TOKEN=${accessToken}\n`;
    environment.ACCESS_TOKEN = accessToken;
  }
  if (needsAccessToken(environment.POINTER_PUSH_SECRET)) {
    if (priorPointerSetup || environment.POINTER_URL) {
      // A new secret cannot update an existing claim. Keep the file intact
      // and let pointer setup surface deliberate credential recovery.
      delete environment.POINTER_PUSH_SECRET;
      console.error(
        JSON.stringify({
          level: "warn",
          event: "pointer_credential_recovery_required",
          message:
            "Restore the original POINTER_PUSH_SECRET from your private backup. Pointer credentials were not replaced.",
        }),
      );
    } else {
      const pointerPushSecret = generateAccessToken();
      contents = /^POINTER_PUSH_SECRET=.*$/m.test(contents)
        ? contents.replace(
            /^POINTER_PUSH_SECRET=.*$/m,
            `POINTER_PUSH_SECRET=${pointerPushSecret}`,
          )
        : `${contents.replace(/\n*$/, "\n")}POINTER_PUSH_SECRET=${pointerPushSecret}\n`;
      environment.POINTER_PUSH_SECRET = pointerPushSecret;
    }
  }
  if (contents !== existing) {
    await writePrivateFile(envPath, contents);
  } else {
    await restrictAccess(envPath);
  }
  return { environment, firstRun: false };
}
