import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

const TOKEN_MINIMUM_LENGTH = 20;

export function parseEnvFile(text) {
  return Object.fromEntries(
    text
      .split(/\r?\n/)
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => {
        const index = line.indexOf("=");
        return [
          line.slice(0, index).trim(),
          line
            .slice(index + 1)
            .trim()
            .replace(/^"(.*)"$/, "$1"),
        ];
      }),
  );
}

export function generateAccessToken() {
  return randomBytes(32).toString("base64url");
}

// A token is unusable if it is missing, too short to resist guessing, or still
// the placeholder shipped in .env.example.
export function needsAccessToken(value) {
  if (!value) return true;
  if (value.length < TOKEN_MINIMUM_LENGTH) return true;
  return value.startsWith("replace-with");
}

// The per-user state directory the packaged app owns. Kept here rather than in
// the supervisor so the same default applies to every entry point.
export function defaultStateRoot(
  platform = process.platform,
  env = process.env,
) {
  if (platform === "win32")
    return join(
      env.LOCALAPPDATA ?? join(homedir(), "AppData", "Local"),
      "HoshiStream",
    );
  return join(homedir(), "Library", "Application Support", "HoshiStream");
}

export function defaultMediaDir(platform = process.platform) {
  return platform === "win32"
    ? join(homedir(), "Videos")
    : join(homedir(), "Movies");
}

function renderEnvFile({
  accessToken,
  pointerPushSecret,
  mediaDir,
  addonPort,
}) {
  return `# Generated by HoshiStream on first run. Edit freely.

ADDON_PORT=${addonPort}

# Guards the management API and appears in your tokenized add-on URL.
ACCESS_TOKEN=${accessToken}

# Folder the app scans for local media.
MEDIA_DIR=${mediaDir}

# Fallback LAN speed (Mbps); the app measures the real link speed at startup.
HOME_SPEED_MBPS=10

# Opt-in stream repair (ADR 0010).
TRANSCODE_ENABLED=false

# Remote pointer (optional, ADR 0013): set POINTER_URL to a pointer server to
# get a permanent add-on URL. The push secret is generated per install and
# claims your token on the first push — it is never shared with anyone.
# POINTER_URL=https://your-pointer.vercel.app
POINTER_PUSH_SECRET=${pointerPushSecret}
`;
}

async function writePrivateFile(path, contents) {
  const temporary = `${path}.tmp`;
  await writeFile(temporary, contents, { mode: 0o600 });
  await rename(temporary, path);
}

/**
 * Make a fresh machine runnable: create the state directory and a .env holding
 * a generated access token. Existing files are preserved; only a missing or
 * placeholder token is replaced. Returns the parsed environment.
 */
export async function ensureFirstRunSetup({
  projectRoot,
  mediaDir = defaultMediaDir(),
  addonPort = 7001,
}) {
  await mkdir(projectRoot, { recursive: true, mode: 0o700 });
  const envPath = join(projectRoot, ".env");

  let existing = null;
  try {
    existing = await readFile(envPath, "utf8");
  } catch {}

  if (existing === null) {
    const accessToken = generateAccessToken();
    const pointerPushSecret = generateAccessToken();
    await writePrivateFile(
      envPath,
      renderEnvFile({ accessToken, pointerPushSecret, mediaDir, addonPort }),
    );
    return { environment: parseEnvFile(await readFile(envPath, "utf8")) };
  }

  const environment = parseEnvFile(existing);
  let contents = existing;
  if (needsAccessToken(environment.ACCESS_TOKEN)) {
    const accessToken = generateAccessToken();
    contents = /^ACCESS_TOKEN=.*$/m.test(contents)
      ? contents.replace(/^ACCESS_TOKEN=.*$/m, `ACCESS_TOKEN=${accessToken}`)
      : `${contents.replace(/\n*$/, "\n")}ACCESS_TOKEN=${accessToken}\n`;
    environment.ACCESS_TOKEN = accessToken;
  }
  // The pointer push secret is per install (ADR 0013); generate it the same
  // way so it is ready whenever the user sets POINTER_URL.
  if (needsAccessToken(environment.POINTER_PUSH_SECRET)) {
    const pointerPushSecret = generateAccessToken();
    contents = /^POINTER_PUSH_SECRET=.*$/m.test(contents)
      ? contents.replace(
          /^POINTER_PUSH_SECRET=.*$/m,
          `POINTER_PUSH_SECRET=${pointerPushSecret}`,
        )
      : `${contents.replace(/\n*$/, "\n")}POINTER_PUSH_SECRET=${pointerPushSecret}\n`;
    environment.POINTER_PUSH_SECRET = pointerPushSecret;
  }
  if (contents !== existing) {
    await writePrivateFile(envPath, contents);
  }
  return { environment };
}
